"""Initial Migration

Revision ID: 5ec4e01159b5
Revises: ae454d2df8c4
Create Date: 2018-11-25 19:44:31.977945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ec4e01159b5'
down_revision = 'ae454d2df8c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Newblog', sa.Column('title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Newblog', 'title')
    # ### end Alembic commands ###
